### ISSUE TITLE
page_path for pages with nodes seems broken

### ISSUE THREAD

**Issue by lexi** [oktavilla/Porthos-Engine#38]
page_path gets double-slashes in the beginning if the page has a node and it doesn't show the whole path only the page's slug.

**Comment by arvida** [comment]
Working of this....

**Comment by joeljunstrom** [comment]
This is due to how we now need to check if we are supposed to give handle to the page path helper all the time.

I suggest we fix the url generation filter to automatically check first if an object has it's own noe, second if it responds to handle (or node handle or w/e) and search for an index node with that. Or something like it

**Comment by lexi** [comment]
Somewhat related?

pages#new needs to print http://domain.com/path/ before the uri field. I've added http://localhost/ as a placeholder.

**Comment by joeljunstrom** [comment]
Resolved by: a257b3e074f41a2fcfdade66064ec388bda65b8e
